/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DistribuerRouteImport } from './routes/distribuer'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CategorieVilleRouteImport } from './routes/$categorie.$ville'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedBienvenueRouteImport } from './routes/_authenticated/bienvenue'
import { Route as AuthenticatedCaisseRouteImport } from './routes/_authenticated/caisse'
import { Route as AuthenticatedStatistiquesRouteImport } from './routes/_authenticated/statistiques'
import { Route as AvisTokenRouteImport } from './routes/avis.$token'
import { Route as ReservationTokenRouteImport } from './routes/reservation.$token'
import { Route as ReserverSlugRouteImport } from './routes/reserver.$slug'
import { Route as SalonSlugRouteImport } from './routes/salon.$slug'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients.$clientId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DistribuerRoute = DistribuerRouteImport.update({
  id: '/distribuer',
  path: '/distribuer',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorieVilleRoute = CategorieVilleRouteImport.update({
  id: '/$categorie/$ville',
  path: '/$categorie/$ville',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBienvenueRoute = AuthenticatedBienvenueRouteImport.update({
  id: '/bienvenue',
  path: '/bienvenue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaisseRoute = AuthenticatedCaisseRouteImport.update({
  id: '/caisse',
  path: '/caisse',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatistiquesRoute =
  AuthenticatedStatistiquesRouteImport.update({
    id: '/statistiques',
    path: '/statistiques',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AvisTokenRoute = AvisTokenRouteImport.update({
  id: '/avis/$token',
  path: '/avis/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationTokenRoute = ReservationTokenRouteImport.update({
  id: '/reservation/$token',
  path: '/reservation/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserverSlugRoute = ReserverSlugRouteImport.update({
  id: '/reserver/$slug',
  path: '/reserver/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonSlugRoute = SalonSlugRouteImport.update({
  id: '/salon/$slug',
  path: '/salon/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/distribuer': typeof DistribuerRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/recherche': typeof RechercheRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$categorie/$ville': typeof CategorieVilleRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/bienvenue': typeof AuthenticatedBienvenueRoute
  '/caisse': typeof AuthenticatedCaisseRoute
  '/statistiques': typeof AuthenticatedStatistiquesRoute
  '/avis/$token': typeof AvisTokenRoute
  '/reservation/$token': typeof ReservationTokenRoute
  '/reserver/$slug': typeof ReserverSlugRoute
  '/salon/$slug': typeof SalonSlugRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/distribuer': typeof DistribuerRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/recherche': typeof RechercheRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$categorie/$ville': typeof CategorieVilleRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/bienvenue': typeof AuthenticatedBienvenueRoute
  '/caisse': typeof AuthenticatedCaisseRoute
  '/statistiques': typeof AuthenticatedStatistiquesRoute
  '/avis/$token': typeof AvisTokenRoute
  '/reservation/$token': typeof ReservationTokenRoute
  '/reserver/$slug': typeof ReserverSlugRoute
  '/salon/$slug': typeof SalonSlugRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/distribuer': typeof DistribuerRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/recherche': typeof RechercheRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$categorie/$ville': typeof CategorieVilleRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/bienvenue': typeof AuthenticatedBienvenueRoute
  '/_authenticated/caisse': typeof AuthenticatedCaisseRoute
  '/_authenticated/statistiques': typeof AuthenticatedStatistiquesRoute
  '/avis/$token': typeof AvisTokenRoute
  '/reservation/$token': typeof ReservationTokenRoute
  '/reserver/$slug': typeof ReserverSlugRoute
  '/salon/$slug': typeof SalonSlugRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/distribuer'
    | '/mentions-legales'
    | '/recherche'
    | '/sitemap.xml'
    | '/$categorie/$ville'
    | '/admin'
    | '/agenda'
    | '/bienvenue'
    | '/caisse'
    | '/statistiques'
    | '/avis/$token'
    | '/reservation/$token'
    | '/reserver/$slug'
    | '/salon/$slug'
    | '/clients/$clientId'
    | '/clients/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/distribuer'
    | '/mentions-legales'
    | '/recherche'
    | '/sitemap.xml'
    | '/$categorie/$ville'
    | '/admin'
    | '/agenda'
    | '/bienvenue'
    | '/caisse'
    | '/statistiques'
    | '/avis/$token'
    | '/reservation/$token'
    | '/reserver/$slug'
    | '/salon/$slug'
    | '/clients/$clientId'
    | '/clients'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/distribuer'
    | '/mentions-legales'
    | '/recherche'
    | '/sitemap.xml'
    | '/$categorie/$ville'
    | '/_authenticated/admin'
    | '/_authenticated/agenda'
    | '/_authenticated/bienvenue'
    | '/_authenticated/caisse'
    | '/_authenticated/statistiques'
    | '/avis/$token'
    | '/reservation/$token'
    | '/reserver/$slug'
    | '/salon/$slug'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/clients/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DistribuerRoute: typeof DistribuerRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  RechercheRoute: typeof RechercheRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CategorieVilleRoute: typeof CategorieVilleRoute
  AvisTokenRoute: typeof AvisTokenRoute
  ReservationTokenRoute: typeof ReservationTokenRoute
  ReserverSlugRoute: typeof ReserverSlugRoute
  SalonSlugRoute: typeof SalonSlugRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribuer': {
      id: '/distribuer'
      path: '/distribuer'
      fullPath: '/distribuer'
      preLoaderRoute: typeof DistribuerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$categorie/$ville': {
      id: '/$categorie/$ville'
      path: '/$categorie/$ville'
      fullPath: '/$categorie/$ville'
      preLoaderRoute: typeof CategorieVilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bienvenue': {
      id: '/_authenticated/bienvenue'
      path: '/bienvenue'
      fullPath: '/bienvenue'
      preLoaderRoute: typeof AuthenticatedBienvenueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caisse': {
      id: '/_authenticated/caisse'
      path: '/caisse'
      fullPath: '/caisse'
      preLoaderRoute: typeof AuthenticatedCaisseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistiques': {
      id: '/_authenticated/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof AuthenticatedStatistiquesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/avis/$token': {
      id: '/avis/$token'
      path: '/avis/$token'
      fullPath: '/avis/$token'
      preLoaderRoute: typeof AvisTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation/$token': {
      id: '/reservation/$token'
      path: '/reservation/$token'
      fullPath: '/reservation/$token'
      preLoaderRoute: typeof ReservationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserver/$slug': {
      id: '/reserver/$slug'
      path: '/reserver/$slug'
      fullPath: '/reserver/$slug'
      preLoaderRoute: typeof ReserverSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon/$slug': {
      id: '/salon/$slug'
      path: '/salon/$slug'
      fullPath: '/salon/$slug'
      preLoaderRoute: typeof SalonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedBienvenueRoute: typeof AuthenticatedBienvenueRoute
  AuthenticatedCaisseRoute: typeof AuthenticatedCaisseRoute
  AuthenticatedStatistiquesRoute: typeof AuthenticatedStatistiquesRoute
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedBienvenueRoute: AuthenticatedBienvenueRoute,
  AuthenticatedCaisseRoute: AuthenticatedCaisseRoute,
  AuthenticatedStatistiquesRoute: AuthenticatedStatistiquesRoute,
  AuthenticatedClientsClientIdRoute: AuthenticatedClientsClientIdRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DistribuerRoute: DistribuerRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  RechercheRoute: RechercheRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CategorieVilleRoute: CategorieVilleRoute,
  AvisTokenRoute: AvisTokenRoute,
  ReservationTokenRoute: ReservationTokenRoute,
  ReserverSlugRoute: ReserverSlugRoute,
  SalonSlugRoute: SalonSlugRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
