GRANT SELECT, INSERT, UPDATE, DELETE ON public.salons TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.employes TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.categories TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.prestations TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.clients TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.rdv TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.encaissements TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.horaires_salon TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.horaires_employe TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.parametres_salon TO authenticated;
GRANT ALL ON public.salons TO service_role;
GRANT ALL ON public.employes TO service_role;
GRANT ALL ON public.categories TO service_role;
GRANT ALL ON public.prestations TO service_role;
GRANT ALL ON public.clients TO service_role;
GRANT ALL ON public.rdv TO service_role;
GRANT ALL ON public.encaissements TO service_role;
GRANT ALL ON public.horaires_salon TO service_role;
GRANT ALL ON public.horaires_employe TO service_role;
GRANT ALL ON public.parametres_salon TO service_role;
GRANT EXECUTE ON FUNCTION public.current_salon_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_gerant() TO authenticated;
GRANT EXECUTE ON FUNCTION public.mon_employe_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.reclamer_invitation() TO authenticated;